# Site settings
author: Carrie L
title: My Data Science Journal
header-img: img/home-bg.png
email: xl309@georgetown.edu
copyright_name: Carrie L
description: > # this means to ignore newlines until "baseurl:"
  Today is a gift; that is why it is called Present.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  carlearn

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
